SELECT DISTINCT(C_CUSTKEY), SUM(C_ACCTBAL), 
SUM(CASE WHEN C_MKTSEGMENT NOT IN ('BUILDING','AUTOMOBILE','MACHINERY','HOUSEHOLD','FURNITURE') THEN 1 ELSE 0 END)  AS MISMATCHES FROM "SNOWFLAKE_SAMPLE_DATA"."TPCH_SF1"."CUSTOMER" 

GROUP BY C_CUSTKEY 

HAVING C_CUSTKEY IS NOT NULL AND 

MISMATCHES > 0 AND 

SUM(C_ACCTBAL) < 100000000 