my_new_project:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: QOGHLFK-EM56083
      user: user_dev
      password: DevUser@123
      role: role_dev
      database: training_1
      warehouse: transforming
      schema: dev_schema
      threads: 1

    test:
      type: snowflake
      account: QOGHLFK-EM56083
      user: user_test
      password: TestUser@123
      role: role_test
      database: training_1
      warehouse: transforming
      schema: test_schema
      threads: 1

    prod:
      type: snowflake
      account: QOGHLFK-EM56083
      user: user_prod
      password: ProdUser@123
      role: role_prod
      database: training_1
      warehouse: transforming
      schema: prod_schema
      threads: 1
